import{a as b,S,i as n}from"./assets/vendor-BIn0hBn5.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))o(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const c of r.addedNodes)c.tagName==="LINK"&&c.rel==="modulepreload"&&o(c)}).observe(document,{childList:!0,subtree:!0});function a(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function o(e){if(e.ep)return;e.ep=!0;const r=a(e);fetch(e.href,r)}})();const w="50866984-6402497f149a27b4d4d3393ca",q="https://pixabay.com/api/";async function m(s,t=1){const a={key:w,q:s,image_type:"photo",orientation:"horizontal",safesearch:!0,page:t,per_page:15};try{return(await b.get(q,{params:a})).data}catch(o){return console.error("Error fetching images:",o),{hits:[],totalHits:0}}}const f=document.querySelector(".gallery");let u;function y(s){const t=s.hits.map(({webformatURL:a,largeImageURL:o,tags:e,likes:r,views:c,comments:v,downloads:L})=>`
      <a class="gallery-item" href="${o}">
        <img src="${a}" alt="${e}" />
        <div class="image-info">
          <div class="stat-item"><span class="stat-label">Likes</span><span class="stat-value">${r}</span></div>
          <div class="stat-item"><span class="stat-label">Views</span><span class="stat-value">${c}</span></div>
          <div class="stat-item"><span class="stat-label">Comments</span><span class="stat-value">${v}</span></div>
          <div class="stat-item"><span class="stat-label">Downloads</span><span class="stat-value">${L}</span></div>
        </div>
      </a>
    `).join("");f.insertAdjacentHTML("beforeend",t),u?u.refresh():u=new S(".gallery a")}function P(){f.innerHTML=""}function p(){document.querySelector(".loader").classList.add("visible")}function h(){document.querySelector(".loader").classList.remove("visible")}function B(){document.querySelector(".load-more").classList.remove("hidden")}function g(){document.querySelector(".load-more").classList.add("hidden")}const $=document.querySelector(".form"),d=document.querySelector(".search-box"),E=document.querySelector(".load-more");let i=1,l="";$.addEventListener("submit",async s=>{if(s.preventDefault(),l=d.value.trim(),i=1,!l){n.error({message:"Please enter a search term!"});return}P(),p(),g();try{const t=await m(l,i);if(t.hits.length===0){n.warning({message:"Sorry, there are no images matching your search query. Please try again!"});return}y(t),t.totalHits>i*15?B():n.info({message:"We're sorry, but you've reached the end of search results."})}catch(t){n.error({message:"Something went wrong. Please try again later."}),console.error(t)}finally{h(),d.value=""}});E.addEventListener("click",async()=>{i++,p();try{const s=await m(l,i);y(s),s.totalHits<=i*15&&(g(),n.info({message:"We're sorry, but you've reached the end of search results."}));const t=document.querySelector(".gallery-item");if(t){const{height:a}=t.getBoundingClientRect();window.scrollBy({top:a*2,behavior:"smooth"})}}catch(s){n.error({message:"Failed to load more images."}),console.error(s)}finally{h()}});
//# sourceMappingURL=index.js.map
